# 端口
server:
  port: 20004
# 应用名称
spring:
  application:
    name: platform-ware
  # nacos
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  # 数据库
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/platform?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss

# Mybatis-Plus
mybatis-plus:
  mapper-locations: /mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto



logging:
  level:
    top.tobing.platform.ware: debug

