server:
  port: 88
spring:
  application:
    name: platform-gateway
  cloud:
    gateway:
      routes:
        # 【库存服务】将 /api/ware 路径重写到 /ware
        - id: ware_route
          uri: lb://platform-ware
          predicates:
            - Path=/api/ware/**
          filters:
            - RewritePath=/api/(?<segment>/?.*), /$\{segment}
        # 【优惠服务】
        - id: coupon_route
          uri: lb://platform-coupon
          predicates:
            - Path=/api/coupon/**
          filters:
            - RewritePath=/api/(?<segment>/?.*), /$\{segment}
        # 【会员服务】将 /api/member 路径重写到 /member
        - id: member_route
          uri: lb://platform-member  # 均衡负载分发到第三方服务
          predicates:
            - Path=/api/member/**
          filters:
            - RewritePath=/api/(?<segment>/?.*), /$\{segment}
        # 【第三方】将 /api/thirypart 路径重写到 /thirypart
        - id: product_route
          uri: lb://platform-thirypart  # 均衡负载分发到第三方服务
          predicates:
            - Path=/api/thirypart/**
          filters:
            - RewritePath=/api/(?<segment>/?.*), /$\{segment}
        # 【product】将 /api/product 路径重写到 /product
        - id: product_route
          uri: lb://platform-product  # 均衡负载分发到product服务
          predicates:
            - Path=/api/product/**,/product/spuinfo/test,/hello
          filters:
            - RewritePath=/api/(?<segment>/?.*), /$\{segment}
        # 【renren-fast】将 /api 路径重写到 /renren-fast
        - id: admin_route
          uri: lb://renren-fast
          predicates:
            - Path=/api/**
          filters:
            - RewritePath=/api/(?<segment>/?.*), /renren-fast/$\{segment}
        # 配置域名映射【首页服务】
        - id: product_index_route
          uri: lb://platform-product
          predicates:
            - Host=www.platform.com,platform.com,item.platform.com
        # 配置域名映射【搜索服务】
        - id: search_index_route
          uri: lb://platform-search
          predicates:
            - Host=search.platform.com
        # 配置域名映射【认证服务】
        - id: auth_index_route
          uri: lb://platform-auth
          predicates:
            - Host=auth.platform.com
        # 配置域名映射【购物车服务】
        - id: cart_index_route
          uri: lb://platform-cart
          predicates:
            - Host=cart.platform.com
        # 配置域名映射【订单服务】
        - id: order_index_route
          uri: lb://platform-order
          predicates:
            - Host=order.platform.com
        # 配置域名映射【秒杀服务】
        - id: seckill_index_route
          uri: lb://platform-seckill
          predicates:
            - Host=seckill.platform.com